# =============================================================================
# 27_build_TBI_TRACT_manuscript_output_data.R
#
# PURPOSE
#   Build the canonical data layer for the final manuscript tables and figures
#   from the LOCKED forward-temporal prediction caches.
#
# IMPORTANT
#   This script does NOT fit or tune any model.
#   It only analyzes predictions already generated by the final locked models.
#
# OUTPUTS
#   - full year-specific classification metrics
#   - pooled rolling-origin forward-temporal evaluation metrics for 2022-2024
#   - 2024 bootstrap CIs for headline classification metrics
#   - flexible spline calibration-curve data
#   - duration performance + 2024 bootstrap CIs
#   - duration calibration-bin data
#   - temporal-performance figure data
#   - subgroup robustness heatmap data
#   - sociodemographic calibration-shift data
#   - key sensitivity summary data
#
# UNCERTAINTY
#   Bootstrap CIs are generated from the fixed rolling-origin forward-temporal evaluation predictions.
#   This quantifies sampling uncertainty of performance in the evaluation cohort;
#   it does not re-fit the full model-development procedure inside each bootstrap.
#
#   Default:
#       classification bootstrap B = 500
#       duration bootstrap B = 1000
#
#   Given the very large evaluation cohorts, these settings are adequate for
#   stable percentile intervals while remaining computationally practical.
# =============================================================================

rm(list = ls())
gc()

required <- c("data.table")
missing_pkgs <- required[
  !vapply(required, requireNamespace, logical(1), quietly = TRUE)
]
if (length(missing_pkgs) > 0L) {
  stop("Missing package(s): ", paste(missing_pkgs, collapse = ", "), call. = FALSE)
}

suppressPackageStartupMessages({
  library(data.table)
})

# -----------------------------------------------------------------------------
# Config / paths
# -----------------------------------------------------------------------------

config_candidates <- c(
  file.path(getwd(), "R", "00_config.R"),
  "R/00_config.R"
)
config_file <- config_candidates[file.exists(config_candidates)[1L]
if (length(config_file) == 0L  || is.na(config_file)) {
  stop("Could not find R/00_config.R.", call. = FALSE)
}
source(config_file)

sens_dir <- file.path(
  output_dir,
  "TBI_TRACT_FINAL_SENSITIVITY_SUITE"
)
class_dir <- file.path(
  output_dir,
  "TBI_TRACT_PRAGMATIC_FINALIST_RETUNE"
)
duration_dir <- file.path(
  output_dir,
  "TBI_TRACT_PRAGMATIC_DURATION_FINALIZATION"
)
methods_dir <- file.path(
  output_dir,
  "METHODS_COMPLETION_TBI_TRACT"
)

pred_dir <- file.path(
  sens_dir,
  "prediction_cache"
)

needed <- c(
  sens_dir,
  class_dir,
  duration_dir,
  pred_dir
)

if (!all(file.exists(needed))) {
  stop(
    "Missing prerequisite output folder(s):\n",
    paste(needed[!file.exists(needed)], collapse = "\n"),
    call. = FALSE
  )
}

out_dir <- file.path(
  output_dir,
  "TBI_TRACT_MANUSCRIPT_OUTPUT_DATA"
)
dir.create(
  out_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

B_CLASSIFICATION <- 500L
B_DURATION <- 1000L
BOOTSTRAP_WORKERS <- max(
  1L,
  min(
    12L,
    parallel::detectCores(logical = TRUE) - 2L
  )
)

# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------

clamp_prob <- function(
    p,
    eps = 1e-7
) {
  pmin(
    pmax(
      as.numeric(p),
      eps
    ),
    1 - eps
  )
}

fast_auc <- function(
    y,
    p
) {
  keep <- !is.na(y) &
    !is.na(p) &
    is.finite(p)

  y <- as.integer(
    y[keep]
  )
  p <- as.numeric(
    p[keep]
  )

  keep2 <- y %in% c(
    0L,
    1L
  )

  y <- y[keep2]
  p <- p[keep2]

  n1 <- as.double(
    sum(
      y == 1L
    )
  )
  n0 <- as.double(
    sum(
      y == 0L
    )
  )

  if (
    n1 == 0 ||
      n0 == 0
  ) {
    return(NA_real_)
  }

  r <- rank(
    p,
    ties.method = "average"
  )

  (
    sum(
      r[
        y == 1L
      ]
    ) -
      n1 *
        (
          n1 + 1
        ) /
        2
  ) /
    (
      n1 *
        n0
    )
}

fast_auprc <- function(
    y,
    p
) {
  keep <- !is.na(y) &
    !is.na(p) &
    is.finite(p)

  y <- as.integer(
    y[keep]
  )
  p <- as.numeric(
    p[keep]
  )

  keep2 <- y %in% c(
    0L,
    1L
  )

  y <- y[keep2]
  p <- p[keep2]

  n_pos <- sum(
    y == 1L
  )

  if (n_pos == 0L) {
    return(NA_real_)
  }

  ord <- order(
    p,
    decreasing = TRUE
  )
  yy <- y[ord]

  tp <- cumsum(
    yy == 1L
  )
  fp <- cumsum(
    yy == 0L
  )

  precision <- tp /
    (
      tp +
        fp
    )

  recall <- tp /
    n_pos

  recall_previous <- c(
    0,
    head(
      recall,
      -1L
    )
  )

  sum(
    precision *
      (
        recall -
          recall_previous
      ),
    na.rm = TRUE
  )
}

binary_calibration <- function(
    y,
    p
) {
  keep <- !is.na(y) &
    !is.na(p) &
    is.finite(p)

  y <- as.integer(
    y[keep]
  )
  p <- clamp_prob(
    p[keep]
  )

  if (
    length(
      unique(
        y
      )
    ) <
      2L
  ) {
    return(
      c(
        intercept = NA_real_,
        slope = NA_real_
      )
    )
  }

  lp <- qlogis(
    p
  )

  fit_i <- tryCatch(
    glm(
      y ~ 1,
      family = binomial(),
      offset = lp
    ),
    error = function(e) NULL
  )

  fit_s <- tryCatch(
    glm(
      y ~ lp,
      family = binomial()
    ),
    error = function(e) NULL
  )

  c(
    intercept =
      if (
        is.null(
          fit_i
        )
      ) {
        NA_real_
      } else {
        unname(
          coef(
            fit_i
          )[1L]
        )
      },
    slope =
      if (
        is.null(
          fit_s
        )
      ) {
        NA_real_
      } else {
        unname(
          coef(
            fit_s
          )["lp"]
        )
      }
  )
}

binary_metrics <- function(
    y,
    p
) {
  pp <- clamp_prob(
    p
  )
  cal <- binary_calibration(
    y,
    p
  )

  data.table(
    N = length(
      y
    ),
    events = sum(
      y == 1L
    ),
    prevalence = mean(
      y == 1L
    ),
    AUROC = fast_auc(
      y,
      p
    ),
    AUPRC = fast_auprc(
      y,
      p
    ),
    AUPRC_to_prevalence =
      fast_auprc(
        y,
        p
      ) /
        mean(
          y == 1L
        ),
    Brier = mean(
      (
        p -
          y
      )^2
    ),
    log_loss =
      -mean(
        y *
          log(
            pp
          ) +
          (
            1 -
              y
          ) *
            log(
              1 -
                pp
            )
      ),
    calibration_intercept =
      unname(
        cal[
          "intercept"
        ]
      ),
    calibration_slope =
      unname(
        cal[
          "slope"
        ]
      )
  )
}

pinball_loss <- function(
    y,
    q,
    alpha
) {
  e <- y - q

  mean(
    ifelse(
      e >= 0,
      alpha *
        e,
      (
        alpha -
          1
      ) *
        e
    ),
    na.rm = TRUE
  )
}

duration_metrics <- function(
    y,
    q10,
    q50,
    q90
) {
  coverage <- mean(
    y >=
      q10 &
      y <=
        q90
  )

  data.table(
    N = length(
      y
    ),
    median_MAE_days =
      mean(
        abs(
          y -
            q50
        )
      ),
    median_bias_days =
      median(
        q50 -
          y
      ),
    mean_pinball =
      mean(
        c(
          pinball_loss(
            y,
            q10,
            0.10
          ),
    ²È="26
# -----------------------------------------------------------------------------
# Subgroup robustness heatmap data
# -----------------------------------------------------------------------------

subgroup_file <- file.path(
  sens_dir,
  "03_FINAL_CLASSIFICATION_SUBGROUP_ROBUSTNESS.csv"
)

subgroup <- fread(
  subgroup_file
)

headline_subgroup <- merge(
  subgroup[
    test_year ==
      2024L
  ],
  headline_targets,
  by = c(
    "endpoint_id",
    "target"
  ),
  all = FALSE
)

overall_2024 <- year_metrics[
  year ==
    2024L
]

overall_2024 <- overall_2024[
  ,
  .(
    endpoint_id,
    target,
    overall_AUROC =
      AUROC,
    overall_AUPRC =
      AUPRC,
    overall_calibration_intercept =
      calibration_intercept,
    overall_calibration_slope =
      calibration_slope
  )
]

headline_subgroup <- merge(
  headline_subgroup,
  overall_2024,
  by = c(
    "endpoint_id",
    "target"
  ),
  all.x = TRUE
)

headline_subgroup[
  ,
  `:=`(
    delta_AUROC_vs_overall =
      AUROC -
        overall_AUROC,
    delta_AUPRC_vs_overall =
      AUPRC -
        overall_AUPRC,
    absolute_calibration_intercept =
      abs(
        calibration_intercept
      ),
    calibration_slope_error =
      abs(
        calibration_slope -
          1
      )
  )
]

fwrite(
  headline_subgroup,
  file.path(
    out_dir,
    "10_2024_SUBGROUP_ROBUSTNESS_HEATMAP_DATA.csv"
  )
)

# -----------------------------------------------------------------------------
# Sociodemographic augmentation figure data
# -----------------------------------------------------------------------------

social_delta_file <- file.path(
  class_dir,
  "10_SYSTEM_MEDIATED_SUBGROUP_DELTAS_VS_PRAGMATIC.csv"
)

social_delta <- fread(
  social_delta_file
)

social_full <- social_delta[
  test_year ==
    2024L &
    variant_id ==
      "PRAGMATIC_PLUS_RACE_ETHNICITY_PAYER"
]

social_full[
  ,
  `:=`(
    reference_abs_calibration_intercept =
      abs(
        calibration_intercept_reference
      ),
    augmented_abs_calibration_intercept =
      abs(
        calibration_intercept
      ),
    improvement_abs_calibration_intercept =
      abs(
        calibration_intercept_reference
      ) -
        abs(
          calibration_intercept
        )
  )
]

fwrite(
  social_full,
  file.path(
    out_dir,
    "11_2024_SOCIAL_AUGMENTATION_CALIBRATION_SHIFT_DATA.csv"
  )
)

# -----------------------------------------------------------------------------
# Key sensitivity summary data
# -----------------------------------------------------------------------------

airway <- fread(
  file.path(
    sens_dir,
    "05_VENTILATION_BASELINE_AIRWAY_STATE_SENSITIVITY.csv"
  )
)

survivor <- fread(
  file.path(
    sens_dir,
    "04_SURVIVOR_ONLY_RESOURCE_TRAJECTORY_SENSITIVITY.csv"
  )
)

composite <- fread(
  file.path(
    sens_dir,
    "10_COMPOSITE_EARLY_DEATH_TEMPORAL_PERFORMANCE.csv"
  )
)

pragmatic_delta <- fread(
  file.path(
    class_dir,
    "07_PRAGMATIC_CLINICAL_VS_CURRENT_TEMPORAL_SUMMARY.csv"
  )
)

duration_delta <- fread(
  file.path(
    duration_dir,
    "06_PRAGMATIC_DURATION_TEMPORAL_SUMMARY.csv"
  )
)

sensitivity_summary <- rbindlist(
  list(
    airway[
      test_year ==
        2024L &
        target ==
          "Ventilation >=8 days",
      .(
        sensitivity_domain =
          "Ventilation timing / leakage",
        comparison =
          airway_state,
        metric =
          "AUROC",
        value =
          AUROC,
        secondary_metric =
          AUPRC
      )
    ],
    survivor[
      test_year ==
        2024L &
        target %in%
          c(
            "ICU >=8 days",
            "Ventilation >=8 days",
            "Hospital LOS >=28 days"
          ),
      .(
        sensitivity_domain =
          "Exclude death/hospice",
        comparison =
          target,
        metric =
          "AUROC",
        value =
          AUROC,
        secondary_metric =
          AUPRC
      )
    ],
    composite[
      test_year ==
        2024L,
      .(
        sensitivity_domain =
          "Death-or-prolonged composite",
        comparison =
          endpoint_label,
        metric =
          "AUROC",
        value =
          AUROC,
        secondary_metric =
          AUPRC
      )
    ],
    pragmatic_delta[
      ,
      .(
        sensitivity_domain =
          "Pragmatic predictor backbone",
        comparison =
          endpoint_label,
        metric =
          "Median delta AUROC",
        value =
          median_delta_AUROC,
        secondary_metric =
          median_delta_AUPRC
      )
    ],
    duration_delta[
      ,
      .(
        sensitivity_domain =
          "Pragmatic duration backbone",
        comparison =
          duration_label,
        metric =
          "Median delta MAE days",
        value =
          median_delta_MAE_days,
        secondary_metric =
          median_delta_pinball
      )
    ]
  ),
  fill = TRUE
)

fwrite(
  sensitivity_summary,
  file.path(
    out_dir,
    "12_KEY_SENSITIVITY_SUMMARY_DATA.csv"
  )
)

# -----------------------------------------------------------------------------
# Output inventory
# -----------------------------------------------------------------------------

inventory <- data.table(
  file = c(
    "01_CLASSIFICATION_YEAR_SPECIFIC_METRICS.csv",
    "02_CLASSIFICATION_POOLED_OOF_METRICS.csv",
    "03_2024_HEADLINE_CLASSIFICATION_BOOTSTRAP_CI.csv",
    "04_2024_FLEXIBLE_CALIBRATION_CURVES.csv",
    "05_2024_CALIBRATION_DECILE_POINTS.csv",
    "06_DURATION_YEAR_SPECIFIC_METRICS.csv",
    "07_2024_DURATION_BOOTSTRAP_CI.csv",
    "08_2024_DURATION_CALIBRATION_BINS.csv",
    "09_TEMPORAL_PERFORMANCE_FIGURE_DATA.csv",
    "10_2024_SUBGROUP_ROBUSTNESS_HEATMAP_DATA.csv",
    "11_2024_SOCIAL_AUGMENTATION_CALIBRATION_SHIFT_DATA.csv",
    "12_KEY_SENSITIVITY_SUMMARY_DATA.csv"
  ),
  intended_use = c(
    "Supplement performance table",
    "Main performance table candidate",
    "Main classification performance table confidence intervals",
    "Main calibration figure",
    "Calibration figure visual anchors",
    "Supplement duration temporal table",
    "Main duration table confidence intervals",
    "Main duration calibration figure",
    "Main temporal-stability figure",
    "Supplement subgroup heatmap",
    "Supplement or main fairness/context figure",
    "Supplement sensitivity summary"
  )
)

fwrite(
  inventory,
  file.path(
    out_dir,
    "13_OUTPUT_DATA_INVENTORY.csv"
  )
)

writeLines(
  c(
    "TBI-TRACT MANUSCRIPT OUTPUT DATA COMPLETE",
    "",
    "No models were fit or tuned in this script.",
    "All performance outputs derive from the locked rolling-origin prediction caches.",
    "",
    "Primary manuscript candidates:",
    "  02_CLASSIFICATION_POOLED_OOF_METRICS.csv",
    "  03_2024_HEADLINE_CLASSIFICATION_BOOTSTRAP_CI.csv",
    "  04_2024_FLEXIBLE_CALIBRATION_CURVES.csv",
    "  07_2024_DURATION_BOOTSTRAP_CI.csv",
    "  08_2024_DURATION_CALIBRATION_BINS.csv",
    "  09_TEMPORAL_PERFORMANCE_FIGURE_DATA.csv",
    "",
    "Calibration curves are flexible spline curves.",
    "Grouped calibration points are provided only as visual anchors, not as a substitute for the smooth curve.",
    "",
    "Q10-Q90 duration outputs should be described as estimated 10th-90th percentile ranges;",
    "empirical coverage is reported rather than assuming exact nominal 80% coverage."
  ),
  file.path(
    out_dir,
    "MANUSCRIPT_OUTPUT_DATA_SUMMARY.txt"
  )
)

cat("\nDONE: ", out_dir, "\n", sep = "")
