# =============================================================================
# 27_build_TBI_TRACT_manuscript_output_data.R
#
# PURPOSE
#   Build the canonical data layer for the final manuscript tables and figures
#   from the LOCKED forward-temporal prediction caches.
#
# IMPORTANT
#   This script does NOT fit or tune any model.
#   It only analyzes predictions already generated by the final locked models.
#
# OUTPUTS
#   - full year-specific classification metrics
#   - pooled rolling-origin out-of-fold (OOF) metrics for 2022-2024
#   - 2024 bootstrap CIs for headline classification metrics
#   - flexible spline calibration-curve data
#   - duration performance + 2024 bootstrap CIs
#   - duration calibration-bin data
#   - temporal-performance figure data
#   - subgroup robustness heatmap data
#   - sociodemographic calibration-shift data
#   - key sensitivity summary data
#
# UNCERTAINTY
#   Bootstrap CIs are generated from the fixed out-of-fold predictions.
#   This quantifies sampling uncertainty of performance in the evaluation cohort;
#   it does not re-fit the full model-development procedure inside each bootstrap.
#
#   Default:
#       classification bootstrap B = 500
#       duration bootstrap B = 1000
#
#   Given the very large evaluation cohorts, these settings are adequate for
#   stable percentile intervals while remaining computationally practical.
# =============================================================================

rm(list = ls())
gc()

required <- c("data.table")
missing_pkgs <- required[
  !vapply(required, requireNamespace, logical(1), quietly = TRUE)
]
if (length(missing_pkgs) > 0L) {
  stop("Missing package(s): ", paste(missing_pkgs, collapse = ", "), call. = FALSE)
}

suppressPackageStartupMessages({
  library(data.table)
})

# -----------------------------------------------------------------------------
# Config / paths
# -----------------------------------------------------------------------------

config_candidates <- c(
  file.path(getwd(), "R", "00_config.R"),
  "R/00_config.R"
)
config_file <- config_candidates[file.exists(config_candidates)][1L]
if (length(config_file) == 0L || is.na(config_file)) {
  stop("Could not find R/00_config.R.", call. = FALSE)
}
source(config_file)

sens_dir <- file.path(
  output_dir,
  "TBI_TRACT_FINAL_SENSITIVITY_SUITE"
)
class_dir <- file.path(
  output_dir,
  "TBI_TRACT_PRAGMATIC_FINALIST_RETUNE"
)
duration_dir <- file.path(
  output_dir,
  "TBI_TRACT_PRAGMATIC_DURATION_FINALIZATION"
)
methods_dir <- file.path(
  output_dir,
  "METHODS_COMPLETION_TBI_TRACT"
)

pred_dir <- file.path(
  sens_dir,
  "prediction_cache"
)

needed <- c(
  sens_dir,
  class_dir,
  duration_dir,
  pred_dir
)

if (!all(file.exists(needed))) {
  stop(
    "Missing prerequisite output folder(s):\n",
    paste(needed[!file.exists(needed)], collapse = "\n"),
    call. = FALSE
  )
}

out_dir <- file.path(
  output_dir,
  "TBI_TRACT_MANUSCRIPT_OUTPUT_DATA"
)
dir.create(
  out_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

B_CLASSIFICATION <- 500L
B_DURATION <- 1000L
BOOTSTRAP_WORKERS <- max(
  1L,
  min(
    12L,
    parallel::detectCores(logical = TRUE) - 2L
  )
)

# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------

clamp_prob <- function(
    p,
    eps = 1e-7
) {
  pmin(
    pmax(
      as.numeric(p),
      eps
    ),
    1 - eps
  )
}

fast_auc <- function(
    y,
    p
) {
  keep <- !is.na(y) &
    !is.na(p) &
    is.finite(p)

  y <- as.integer(
    y[keep]
  )
  p <- as.numeric(
    p[keep]
  )

  keep2 <- y %in% c(
    0L,
    1L
  )

  y <- y[keep2]
  p <- p[keep2]

  n1 <- as.double(
    sum(
      y == 1L
    )
  )
  n0 <- as.double(
    sum(
      y == 0L
    )
  )

  if (
    n1 == 0 ||
      n0 == 0
  ) {
    return(NA_real_)
  }

  r <- rank(
    p,
    ties.method = "average"
  )

  (
    sum(
      r[
        y == 1L
      ]
    ) -
      n1 *
        (
          n1 + 1
        ) /
        2
  ) /
    (
      n1 *
        n0
    )
}

fast_auprc <- function(
    y,
    p
) {
  keep <- !is.na(y) &
    !is.na(p) &
    is.finite(p)

  y <- as.integer(
    y[keep]
  )
  p <- as.numeric(
    p[keep]
  )

  keep2 <- y %in% c(
    0L,
    1L
  )

  y <- y[keep2]
  p <- p[keep2]

  n_pos <- sum(
    y == 1L
  )

  if (n_pos == 0L) {
    return(NA_real_)
  }

  ord <- order(
    p,
    decreasing = TRUE
  )
  yy <- y[ord]

  tp <- cumsum(
    yy == 1L
  )
  fp <- cumsum(
    yy == 0L
  )

  precision <- tp /
    (
      tp +
        fp
    )

  recall <- tp /
    n_pos

  recall_previous <- c(
    0,
    head(
      recall,
      -1L
    )
  )

  sum(
    precision *
      (
        recall -
          recall_previous
      ),
    na.rm = TRUE
  )
}

binary_calibration <- function(
    y,
    p
) {
  keep <- !is.na(y) &
    !is.na(p) &
    is.finite(p)

  y <- as.integer(
    y[keep]
  )
  p <- clamp_prob(
    p[keep]
  )

  if (
    length(
      unique(
        y
      )
    ) <
      2L
  ) {
    return(
      c(
        intercept = NA_real_,
        slope = NA_real_
      )
    )
  }

  lp <- qlogis(
    p
  )

  fit_i <- tryCatch(
    glm(
      y ~ 1,
      family = binomial(),
      offset = lp
    ),
    error = function(e) NULL
  )

  fit_s <- tryCatch(
    glm(
      y ~ lp,
      family = binomial()
    ),
    error = function(e) NULL
  )

  c(
    intercept =
      if (
        is.null(
          fit_i
        )
      ) {
        NA_real_
      } else {
        unname(
          coef(
            fit_i
          )[1L]
        )
      },
    slope =
      if (
        is.null(
          fit_s
        )
      ) {
        NA_real_
      } else {
        unname(
          coef(
            fit_s
          )["lp"]
        )
      }
  )
}

binary_metrics <- function(
    y,
    p
) {
  pp <- clamp_prob(
    p
  )
  cal <- binary_calibration(
    y,
    p
  )

  data.table(
    N = length(
      y
    ),
    events = sum(
      y == 1L
    ),
    prevalence = mean(
      y == 1L
    ),
    AUROC = fast_auc(
      y,
      p
    ),
    AUPRC = fast_auprc(
      y,
      p
    ),
    AUPRC_to_prevalence =
      fast_auprc(
        y,
        p
      ) /
        mean(
          y == 1L
        ),
    Brier = mean(
      (
        p -
          y
      )^2
    ),
    log_loss =
      -mean(
        y *
          log(
            pp
          ) +
          (
            1 -
              y
          ) *
            log(
              1 -
                pp
            )
      ),
    calibration_intercept =
      unname(
        cal[
          "intercept"
        ]
      ),
    calibration_slope =
      unname(
        cal[
          "slope"
        ]
      )
  )
}

pinball_loss <- function(
    y,
    q,
    alpha
) {
  e <- y - q

  mean(
    ifelse(
      e >= 0,
      alpha *
        e,
      (
        alpha -
          1
      ) *
        e
    ),
    na.rm = TRUE
  )
}

duration_metrics <- function(
    y,
    q10,
    q50,
    q90
) {
  coverage <- mean(
    y >=
      q10 &
      y <=
        q90
  )

  data.table(
    N = length(
      y
    ),
    median_MAE_days =
      mean(
        abs(
          y -
            q50
        )
      ),
    median_bias_days =
      median(
        q50 -
          y
      ),
    mean_pinball =
      mean(
        c(
          pinball_loss(
            y,
            q10,
            0.10
          ),
          pinball_loss(
            y,
            q50,
            0.50
          ),
          pinball_loss(
            y,
            q90,
            0.90
          )
        )
      ),
    empirical_q10 =
      mean(
        y <=
          q10
      ),
    empirical_q50 =
      mean(
        y <=
          q50
      ),
    empirical_q90 =
      mean(
        y <=
          q90
      ),
    central_80_coverage =
      coverage,
    median_80_range_width_days =
      median(
        q90 -
          q10
      )
  )
}

bootstrap_binary_ci <- function(
    y,
    p,
    B = B_CLASSIFICATION,
    workers = BOOTSTRAP_WORKERS,
    seed = 20260913L
) {
  y <- as.integer(
    y
  )
  p <- as.numeric(
    p
  )
  n <- length(
    y
  )

  point <- binary_metrics(
    y,
    p
  )

  worker_metric <- function(
      b,
      y,
      p,
      seed
  ) {
    set.seed(
      seed +
        b
    )

    idx <- sample.int(
      length(
        y
      ),
      replace = TRUE
    )

    yy <- y[
      idx
    ]
    pp <- p[
      idx
    ]

    auc_local <- function(y, p) {
      n1 <- as.double(
        sum(
          y == 1L
        )
      )
      n0 <- as.double(
        sum(
          y == 0L
        )
      )

      if (
        n1 == 0 ||
          n0 == 0
      ) {
        return(
          NA_real_
        )
      }

      r <- rank(
        p,
        ties.method = "average"
      )

      (
        sum(
          r[
            y == 1L
          ]
        ) -
          n1 *
            (
              n1 + 1
            ) /
            2
      ) /
        (
          n1 *
            n0
        )
    }

    auprc_local <- function(y, p) {
      n_pos <- sum(
        y == 1L
      )

      if (
        n_pos == 0L
      ) {
        return(
          NA_real_
        )
      }

      ord <- order(
        p,
        decreasing = TRUE
      )
      ys <- y[
        ord
      ]

      tp <- cumsum(
        ys == 1L
      )
      fp <- cumsum(
        ys == 0L
      )

      precision <- tp /
        (
          tp +
            fp
        )
      recall <- tp /
        n_pos
      recall_previous <- c(
        0,
        head(
          recall,
          -1L
        )
      )

      sum(
        precision *
          (
            recall -
              recall_previous
          ),
        na.rm = TRUE
      )
    }

    c(
      AUROC =
        auc_local(
          yy,
          pp
        ),
      AUPRC =
        auprc_local(
          yy,
          pp
        ),
      Brier =
        mean(
          (
            pp -
              yy
          )^2
        )
    )
  }

  cl <- parallel::makeCluster(
    workers
  )
  on.exit(
    parallel::stopCluster(
      cl
    ),
    add = TRUE
  )

  reps <- parallel::parLapply(
    cl,
    seq_len(
      B
    ),
    worker_metric,
    y = y,
    p = p,
    seed = seed
  )

  reps <- do.call(
    rbind,
    reps
  )

  data.table(
    N = point$N,
    events = point$events,
    prevalence = point$prevalence,
    AUROC = point$AUROC,
    AUROC_low =
      quantile(
        reps[
          ,
          "AUROC"
        ],
        0.025,
        na.rm = TRUE
      ),
    AUROC_high =
      quantile(
        reps[
          ,
          "AUROC"
        ],
        0.975,
        na.rm = TRUE
      ),
    AUPRC = point$AUPRC,
    AUPRC_low =
      quantile(
        reps[
          ,
          "AUPRC"
        ],
        0.025,
        na.rm = TRUE
      ),
    AUPRC_high =
      quantile(
        reps[
          ,
          "AUPRC"
        ],
        0.975,
        na.rm = TRUE
      ),
    AUPRC_to_prevalence =
      point$AUPRC_to_prevalence,
    Brier = point$Brier,
    Brier_low =
      quantile(
        reps[
          ,
          "Brier"
        ],
        0.025,
        na.rm = TRUE
      ),
    Brier_high =
      quantile(
        reps[
          ,
          "Brier"
        ],
        0.975,
        na.rm = TRUE
      ),
    calibration_intercept =
      point$calibration_intercept,
    calibration_slope =
      point$calibration_slope,
    bootstrap_B =
      B
  )
}

bootstrap_duration_ci <- function(
    y,
    q10,
    q50,
    q90,
    B = B_DURATION,
    seed = 20260913L
) {
  point <- duration_metrics(
    y,
    q10,
    q50,
    q90
  )

  set.seed(
    seed
  )

  reps <- matrix(
    NA_real_,
    nrow = B,
    ncol = 4L
  )

  colnames(
    reps
  ) <- c(
    "MAE",
    "pinball",
    "coverage",
    "width"
  )

  n <- length(
    y
  )

  for (
    b in seq_len(
      B
    )
  ) {
    idx <- sample.int(
      n,
      replace = TRUE
    )

    yy <- y[
      idx
    ]
    l <- q10[
      idx
    ]
    m <- q50[
      idx
    ]
    u <- q90[
      idx
    ]

    reps[
      b,
      "MAE"
    ] <- mean(
      abs(
        yy -
          m
      )
    )

    reps[
      b,
      "pinball"
    ] <- mean(
      c(
        pinball_loss(
          yy,
          l,
          0.10
        ),
        pinball_loss(
          yy,
          m,
          0.50
        ),
        pinball_loss(
          yy,
          u,
          0.90
        )
      )
    )

    reps[
      b,
      "coverage"
    ] <- mean(
      yy >=
        l &
        yy <=
          u
    )

    reps[
      b,
      "width"
    ] <- median(
      u -
        l
    )
  }

  data.table(
    N =
      point$N,
    median_MAE_days =
      point$median_MAE_days,
    MAE_low =
      quantile(
        reps[
          ,
          "MAE"
        ],
        0.025
      ),
    MAE_high =
      quantile(
        reps[
          ,
          "MAE"
        ],
        0.975
      ),
    mean_pinball =
      point$mean_pinball,
    pinball_low =
      quantile(
        reps[
          ,
          "pinball"
        ],
        0.025
      ),
    pinball_high =
      quantile(
        reps[
          ,
          "pinball"
        ],
        0.975
      ),
    central_80_coverage =
      point$central_80_coverage,
    coverage_low =
      quantile(
        reps[
          ,
          "coverage"
        ],
        0.025
      ),
    coverage_high =
      quantile(
        reps[
          ,
          "coverage"
        ],
        0.975
      ),
    median_80_range_width_days =
      point$median_80_range_width_days,
    width_low =
      quantile(
        reps[
          ,
          "width"
        ],
        0.025
      ),
    width_high =
      quantile(
        reps[
          ,
          "width"
        ],
        0.975
      ),
    empirical_q10 =
      point$empirical_q10,
    empirical_q50 =
      point$empirical_q50,
    empirical_q90 =
      point$empirical_q90,
    bootstrap_B =
      B
  )
}

flexible_calibration_curve <- function(
    y,
    p,
    n_grid = 150L
) {
  p <- clamp_prob(
    p
  )
  y <- as.integer(
    y
  )

  lp <- qlogis(
    p
  )

  fit <- glm(
    y ~ splines::ns(
      lp,
      df = 4
    ),
    family = binomial()
  )

  q <- quantile(
    p,
    probs = c(
      0.005,
      0.995
    ),
    na.rm = TRUE
  )

  grid_p <- seq(
    q[1L],
    q[2L],
    length.out = n_grid
  )

  newdata <- data.frame(
    lp =
      qlogis(
        clamp_prob(
          grid_p
        )
      )
  )

  pr <- predict(
    fit,
    newdata = newdata,
    type = "link",
    se.fit = TRUE
  )

  eta <- as.numeric(
    pr$fit
  )
  se <- as.numeric(
    pr$se.fit
  )

  data.table(
    predicted_probability =
      grid_p,
    calibrated_probability =
      plogis(
        eta
      ),
    lower_95 =
      plogis(
        eta -
          1.96 *
            se
      ),
    upper_95 =
      plogis(
        eta +
          1.96 *
            se
      )
  )
}

prob_col <- function(label) {
  paste0(
    "p__",
    make.names(
      label,
      unique = TRUE
    )
  )
}

# -----------------------------------------------------------------------------
# Endpoint metadata
# -----------------------------------------------------------------------------

class_specs <- list(
  discharge_3cat_final = list(
    label = "Disposition",
    classes = c(
      "Home/home health",
      "Post-acute facility",
      "Death/hospice"
    ),
    derived = NULL
  ),
  icu_trajectory_final = list(
    label = "ICU trajectory",
    classes = c(
      "No ICU",
      "ICU 1-7 days",
      "ICU >=8 days"
    ),
    derived = list(
      label = "Any ICU",
      reference_class = "No ICU"
    )
  ),
  ventilation_trajectory_final = list(
    label = "Mechanical ventilation trajectory",
    classes = c(
      "No ventilation",
      "Ventilation 1-7 days",
      "Ventilation >=8 days"
    ),
    derived = list(
      label = "Any ventilation",
      reference_class = "No ventilation"
    )
  ),
  hlos_trajectory_final = list(
    label = "Hospital LOS trajectory",
    classes = c(
      "Hospital LOS <=7 days",
      "Hospital LOS 8-27 days",
      "Hospital LOS >=28 days"
    ),
    derived = NULL
  ),
  icp_pressure_monitor_final = list(
    label = "Invasive ICP monitoring",
    classes = NULL,
    derived = NULL
  ),
  craniotomy_craniectomy_final = list(
    label = "Craniotomy/craniectomy",
    classes = NULL,
    derived = NULL
  )
)

duration_specs <- list(
  hospital_los = "Hospital LOS",
  icu_los_conditional = "ICU LOS conditional on ICU use",
  ventilator_days_conditional = "Ventilator duration conditional on ventilation"
)

headline_targets <- data.table(
  endpoint_id = c(
    "discharge_3cat_final",
    "discharge_3cat_final",
    "icu_trajectory_final",
    "icu_trajectory_final",
    "ventilation_trajectory_final",
    "ventilation_trajectory_final",
    "hlos_trajectory_final",
    "icp_pressure_monitor_final",
    "craniotomy_craniectomy_final"
  ),
  target = c(
    "Post-acute facility",
    "Death/hospice",
    "Any ICU",
    "ICU >=8 days",
    "Any ventilation",
    "Ventilation >=8 days",
    "Hospital LOS >=28 days",
    "Invasive ICP monitoring",
    "Craniotomy/craniectomy"
  )
)

# -----------------------------------------------------------------------------
# Build binary target extracts from prediction caches
# -----------------------------------------------------------------------------

extract_targets <- function(
    cache,
    endpoint_id
) {
  spec <- class_specs[[endpoint_id]]
  out <- list()

  if (
    endpoint_id %in%
      c(
        "icp_pressure_monitor_final",
        "craniotomy_craniectomy_final"
      )
  ) {
    out[[1L]] <- data.table(
      endpoint_id =
        endpoint_id,
      endpoint_label =
        spec$label,
      target =
        spec$label,
      observed =
        as.integer(
          cache$observed
        ),
      probability =
        as.numeric(
          cache$predicted_probability
        )
    )

    return(
      out
    )
  }

  for (
    class_label in spec$classes
  ) {
    pc <- prob_col(
      class_label
    )

    if (
      !pc %in%
        names(
          cache
        )
    ) {
      stop(
        "Prediction column missing: ",
        pc,
        call. = FALSE
      )
    }

    out[[
      length(
        out
      ) +
        1L
    ]] <- data.table(
      endpoint_id =
        endpoint_id,
      endpoint_label =
        spec$label,
      target =
        class_label,
      observed =
        as.integer(
          as.character(
            cache$observed
          ) ==
            class_label
        ),
      probability =
        as.numeric(
          cache[[pc]]
        )
    )
  }

  if (
    !is.null(
      spec$derived
    )
  ) {
    ref <- spec$derived$reference_class
    pc <- prob_col(
      ref
    )

    out[[
      length(
        out
      ) +
        1L
    ]] <- data.table(
      endpoint_id =
        endpoint_id,
      endpoint_label =
        spec$label,
      target =
        spec$derived$label,
      observed =
        as.integer(
          as.character(
            cache$observed
          ) !=
            ref
        ),
      probability =
        1 -
          as.numeric(
            cache[[pc]]
          )
    )
  }

  out
}

# -----------------------------------------------------------------------------
# Year-specific and pooled OOF classification metrics
# -----------------------------------------------------------------------------

year_rows <- list()
pooled_target_data <- list()

for (
  endpoint_id in names(
    class_specs
  )
) {
  pooled_parts <- list()

  for (
    year in 2022:2024
  ) {
    fold_name <- paste0(
      "TEST_",
      year
    )

    f <- file.path(
      pred_dir,
      paste0(
        fold_name,
        "__",
        endpoint_id,
        "__final_predictions.rds"
      )
    )

    if (
      !file.exists(
        f
      )
    ) {
      stop(
        "Missing prediction cache: ",
        f,
        call. = FALSE
      )
    }

    cache <- as.data.table(
      readRDS(
        f
      )
    )

    targets <- extract_targets(
      cache,
      endpoint_id
    )

    for (
      d in targets
    ) {
      met <- binary_metrics(
        d$observed,
        d$probability
      )

      met[
        ,
        `:=`(
          year =
            year,
          endpoint_id =
            d$endpoint_id[1L],
          endpoint_label =
            d$endpoint_label[1L],
          target =
            d$target[1L]
        )
      ]

      year_rows[[
        length(
          year_rows
        ) +
          1L
      ]] <- met

      pooled_parts[[
        paste0(
          year,
          "__",
          d$target[1L]
        )
      ]] <- copy(
        d
      )[
        ,
        year :=
          year
      ]
    }
  }

  pooled_target_data[[
    endpoint_id
  ]] <- rbindlist(
    pooled_parts,
    fill = TRUE
  )
}

year_metrics <- rbindlist(
  year_rows,
  fill = TRUE
)

fwrite(
  year_metrics[
    order(
      endpoint_label,
      target,
      year
    )
  ],
  file.path(
    out_dir,
    "01_CLASSIFICATION_YEAR_SPECIFIC_METRICS.csv"
  )
)

pooled_rows <- list()

for (
  endpoint_id in names(
    pooled_target_data
  )
) {
  d <- pooled_target_data[[
    endpoint_id
  ]]

  for (
    target_name in unique(
      d$target
    )
  ) {
    dd <- d[
      target ==
        target_name
    ]

    met <- binary_metrics(
      dd$observed,
      dd$probability
    )

    met[
      ,
      `:=`(
        years =
          "2022-2024 rolling-origin OOF",
        endpoint_id =
          endpoint_id,
        endpoint_label =
          dd$endpoint_label[1L],
        target =
          target_name
      )
    ]

    pooled_rows[[
      length(
        pooled_rows
      ) +
        1L
    ]] <- met
  }
}

pooled_metrics <- rbindlist(
  pooled_rows,
  fill = TRUE
)

fwrite(
  pooled_metrics[
    order(
      endpoint_label,
      target
    )
  ],
  file.path(
    out_dir,
    "02_CLASSIFICATION_POOLED_OOF_METRICS.csv"
  )
)

# -----------------------------------------------------------------------------
# 2024 bootstrap CIs for headline classification targets
# -----------------------------------------------------------------------------

headline_ci_rows <- list()

for (
  i in seq_len(
    nrow(
      headline_targets
    )
  )
) {
  endpoint_id <- headline_targets$endpoint_id[i]
  target_name <- headline_targets$target[i]

  fold_name <- "TEST_2024"

  f <- file.path(
    pred_dir,
    paste0(
      fold_name,
      "__",
      endpoint_id,
      "__final_predictions.rds"
    )
  )

  cache <- as.data.table(
    readRDS(
      f
    )
  )

  targets <- extract_targets(
    cache,
    endpoint_id
  )

  d <- rbindlist(
    targets,
    fill = TRUE
  )[
    target ==
      target_name
  ]

  if (
    nrow(
      d
    ) ==
      0L
  ) {
    stop(
      "Could not recover headline target: ",
      endpoint_id,
      " / ",
      target_name,
      call. = FALSE
    )
  }

  cat(
    "\nBootstrap classification CI: ",
    target_name,
    "\n",
    sep = ""
  )

  ci <- bootstrap_binary_ci(
    d$observed,
    d$probability,
    B = B_CLASSIFICATION,
    workers = BOOTSTRAP_WORKERS,
    seed =
      20260913L +
        i *
          1000L
  )

  ci[
    ,
    `:=`(
      year =
        2024L,
      endpoint_id =
        endpoint_id,
      endpoint_label =
        d$endpoint_label[1L],
      target =
        target_name
    )
  ]

  headline_ci_rows[[
    length(
      headline_ci_rows
    ) +
      1L
  ]] <- ci
}

headline_ci <- rbindlist(
  headline_ci_rows,
  fill = TRUE
)

fwrite(
  headline_ci,
  file.path(
    out_dir,
    "03_2024_HEADLINE_CLASSIFICATION_BOOTSTRAP_CI.csv"
  )
)

# -----------------------------------------------------------------------------
# Flexible 2024 calibration curves
# -----------------------------------------------------------------------------

calibration_rows <- list()
calibration_group_rows <- list()

for (
  i in seq_len(
    nrow(
      headline_targets
    )
  )
) {
  endpoint_id <- headline_targets$endpoint_id[i]
  target_name <- headline_targets$target[i]

  f <- file.path(
    pred_dir,
    paste0(
      "TEST_2024__",
      endpoint_id,
      "__final_predictions.rds"
    )
  )

  cache <- as.data.table(
    readRDS(
      f
    )
  )

  d <- rbindlist(
    extract_targets(
      cache,
      endpoint_id
    ),
    fill = TRUE
  )[
    target ==
      target_name
  ]

  curve <- flexible_calibration_curve(
    d$observed,
    d$probability
  )

  curve[
    ,
    `:=`(
      endpoint_id =
        endpoint_id,
      endpoint_label =
        d$endpoint_label[1L],
      target =
        target_name,
      year =
        2024L
    )
  ]

  calibration_rows[[
    length(
      calibration_rows
    ) +
      1L
  ]] <- curve

  # Decile points are supplemental visual anchors only; the smooth curve is
  # the primary calibration assessment.
  dd <- data.table(
    y =
      d$observed,
    p =
      d$probability
  )

  dd[
    ,
    group :=
      pmin(
        10L,
        pmax(
          1L,
          ceiling(
            10 *
              frank(
                p,
                ties.method = "average"
              ) /
              .N
          )
        )
      )
  ]

  gp <- dd[
    ,
    .(
      N =
        .N,
      mean_predicted =
        mean(
          p
        ),
      observed =
        mean(
          y
        )
    ),
    by = group
  ]

  gp[
    ,
    `:=`(
      endpoint_id =
        endpoint_id,
      endpoint_label =
        d$endpoint_label[1L],
      target =
        target_name,
      year =
        2024L
    )
  ]

  calibration_group_rows[[
    length(
      calibration_group_rows
    ) +
      1L
  ]] <- gp
}

calibration_curves <- rbindlist(
  calibration_rows,
  fill = TRUE
)

calibration_points <- rbindlist(
  calibration_group_rows,
  fill = TRUE
)

fwrite(
  calibration_curves,
  file.path(
    out_dir,
    "04_2024_FLEXIBLE_CALIBRATION_CURVES.csv"
  )
)

fwrite(
  calibration_points,
  file.path(
    out_dir,
    "05_2024_CALIBRATION_DECILE_POINTS.csv"
  )
)

# -----------------------------------------------------------------------------
# Duration metrics, bootstrap CIs, and calibration bins
# -----------------------------------------------------------------------------

duration_year_rows <- list()
duration_ci_rows <- list()
duration_calibration_rows <- list()

for (
  duration_id in names(
    duration_specs
  )
) {
  label <- duration_specs[[
    duration_id
  ]]

  for (
    year in 2022:2024
  ) {
    f <- file.path(
      pred_dir,
      paste0(
        "TEST_",
        year,
        "__",
        duration_id,
        "__final_duration_predictions.rds"
      )
    )

    cache <- as.data.table(
      readRDS(
        f
      )
    )

    met <- duration_metrics(
      cache$observed_days,
      cache$q10,
      cache$q50,
      cache$q90
    )

    met[
      ,
      `:=`(
        year =
          year,
        duration_id =
          duration_id,
        duration_label =
          label
      )
    ]

    duration_year_rows[[
      length(
        duration_year_rows
      ) +
        1L
    ]] <- met

    if (
      year ==
        2024L
    ) {
      cat(
        "\nBootstrap duration CI: ",
        label,
        "\n",
        sep = ""
      )

      ci <- bootstrap_duration_ci(
        cache$observed_days,
        cache$q10,
        cache$q50,
        cache$q90,
        B = B_DURATION,
        seed =
          20260913L +
            length(
              duration_ci_rows
            ) *
              1000L
      )

      ci[
        ,
        `:=`(
          year =
            2024L,
          duration_id =
            duration_id,
          duration_label =
            label
        )
      ]

      duration_ci_rows[[
        length(
          duration_ci_rows
        ) +
          1L
      ]] <- ci

      d <- copy(
        cache
      )

      d[
        ,
        bin :=
          pmin(
            20L,
            pmax(
              1L,
              ceiling(
                20 *
                  frank(
                    q50,
                    ties.method = "average"
                  ) /
                  .N
              )
            )
          )
      ]

      cal <- d[
        ,
        .(
          N =
            .N,
          predicted_median =
            median(
              q50
            ),
          observed_median =
            median(
              observed_days
            ),
          predicted_q10 =
            median(
              q10
            ),
          predicted_q90 =
            median(
              q90
            ),
          observed_q10 =
            quantile(
              observed_days,
              0.10
            ),
          observed_q90 =
            quantile(
              observed_days,
              0.90
            )
        ),
        by = bin
      ]

      cal[
        ,
        `:=`(
          duration_id =
            duration_id,
          duration_label =
            label,
          year =
            2024L
        )
      ]

      duration_calibration_rows[[
        length(
          duration_calibration_rows
        ) +
          1L
      ]] <- cal
    }
  }
}

duration_year <- rbindlist(
  duration_year_rows,
  fill = TRUE
)

duration_ci <- rbindlist(
  duration_ci_rows,
  fill = TRUE
)

duration_calibration <- rbindlist(
  duration_calibration_rows,
  fill = TRUE
)

fwrite(
  duration_year,
  file.path(
    out_dir,
    "06_DURATION_YEAR_SPECIFIC_METRICS.csv"
  )
)

fwrite(
  duration_ci,
  file.path(
    out_dir,
    "07_2024_DURATION_BOOTSTRAP_CI.csv"
  )
)

fwrite(
  duration_calibration,
  file.path(
    out_dir,
    "08_2024_DURATION_CALIBRATION_BINS.csv"
  )
)

# -----------------------------------------------------------------------------
# Temporal-performance figure data
# -----------------------------------------------------------------------------

temporal_figure <- merge(
  year_metrics,
  headline_targets,
  by = c(
    "endpoint_id",
    "target"
  ),
  all = FALSE
)

temporal_figure[
  ,
  prevalence_lift :=
    AUPRC_to_prevalence
]

fwrite(
  temporal_figure[
    order(
      endpoint_label,
      target,
      year
    )
  ],
  file.path(
    out_dir,
    "09_TEMPORAL_PERFORMANCE_FIGURE_DATA.csv"
  )
)

# -----------------------------------------------------------------------------
# Subgroup robustness heatmap data
# -----------------------------------------------------------------------------

subgroup_file <- file.path(
  sens_dir,
  "03_FINAL_CLASSIFICATION_SUBGROUP_ROBUSTNESS.csv"
)

subgroup <- fread(
  subgroup_file
)

headline_subgroup <- merge(
  subgroup[
    test_year ==
      2024L
  ],
  headline_targets,
  by = c(
    "endpoint_id",
    "target"
  ),
  all = FALSE
)

overall_2024 <- year_metrics[
  year ==
    2024L
]

overall_2024 <- overall_2024[
  ,
  .(
    endpoint_id,
    target,
    overall_AUROC =
      AUROC,
    overall_AUPRC =
      AUPRC,
    overall_calibration_intercept =
      calibration_intercept,
    overall_calibration_slope =
      calibration_slope
  )
]

headline_subgroup <- merge(
  headline_subgroup,
  overall_2024,
  by = c(
    "endpoint_id",
    "target"
  ),
  all.x = TRUE
)

headline_subgroup[
  ,
  `:=`(
    delta_AUROC_vs_overall =
      AUROC -
        overall_AUROC,
    delta_AUPRC_vs_overall =
      AUPRC -
        overall_AUPRC,
    absolute_calibration_intercept =
      abs(
        calibration_intercept
      ),
    calibration_slope_error =
      abs(
        calibration_slope -
          1
      )
  )
]

fwrite(
  headline_subgroup,
  file.path(
    out_dir,
    "10_2024_SUBGROUP_ROBUSTNESS_HEATMAP_DATA.csv"
  )
)

# -----------------------------------------------------------------------------
# Sociodemographic augmentation figure data
# -----------------------------------------------------------------------------

social_delta_file <- file.path(
  class_dir,
  "10_SYSTEM_MEDIATED_SUBGROUP_DELTAS_VS_PRAGMATIC.csv"
)

social_delta <- fread(
  social_delta_file
)

social_full <- social_delta[
  test_year ==
    2024L &
    variant_id ==
      "PRAGMATIC_PLUS_RACE_ETHNICITY_PAYER"
]

social_full[
  ,
  `:=`(
    reference_abs_calibration_intercept =
      abs(
        calibration_intercept_reference
      ),
    augmented_abs_calibration_intercept =
      abs(
        calibration_intercept
      ),
    improvement_abs_calibration_intercept =
      abs(
        calibration_intercept_reference
      ) -
        abs(
          calibration_intercept
        )
  )
]

fwrite(
  social_full,
  file.path(
    out_dir,
    "11_2024_SOCIAL_AUGMENTATION_CALIBRATION_SHIFT_DATA.csv"
  )
)

# -----------------------------------------------------------------------------
# Key sensitivity summary data
# -----------------------------------------------------------------------------

airway <- fread(
  file.path(
    sens_dir,
    "05_VENTILATION_BASELINE_AIRWAY_STATE_SENSITIVITY.csv"
  )
)

survivor <- fread(
  file.path(
    sens_dir,
    "04_SURVIVOR_ONLY_RESOURCE_TRAJECTORY_SENSITIVITY.csv"
  )
)

composite <- fread(
  file.path(
    sens_dir,
    "10_COMPOSITE_EARLY_DEATH_TEMPORAL_PERFORMANCE.csv"
  )
)

pragmatic_delta <- fread(
  file.path(
    class_dir,
    "07_PRAGMATIC_CLINICAL_VS_CURRENT_TEMPORAL_SUMMARY.csv"
  )
)

duration_delta <- fread(
  file.path(
    duration_dir,
    "06_PRAGMATIC_DURATION_TEMPORAL_SUMMARY.csv"
  )
)

sensitivity_summary <- rbindlist(
  list(
    airway[
      test_year ==
        2024L &
        target ==
          "Ventilation >=8 days",
      .(
        sensitivity_domain =
          "Ventilation timing / leakage",
        comparison =
          airway_state,
        metric =
          "AUROC",
        value =
          AUROC,
        secondary_metric =
          AUPRC
      )
    ],
    survivor[
      test_year ==
        2024L &
        target %in%
          c(
            "ICU >=8 days",
            "Ventilation >=8 days",
            "Hospital LOS >=28 days"
          ),
      .(
        sensitivity_domain =
          "Exclude death/hospice",
        comparison =
          target,
        metric =
          "AUROC",
        value =
          AUROC,
        secondary_metric =
          AUPRC
      )
    ],
    composite[
      test_year ==
        2024L,
      .(
        sensitivity_domain =
          "Death-or-prolonged composite",
        comparison =
          endpoint_label,
        metric =
          "AUROC",
        value =
          AUROC,
        secondary_metric =
          AUPRC
      )
    ],
    pragmatic_delta[
      ,
      .(
        sensitivity_domain =
          "Pragmatic predictor backbone",
        comparison =
          endpoint_label,
        metric =
          "Median delta AUROC",
        value =
          median_delta_AUROC,
        secondary_metric =
          median_delta_AUPRC
      )
    ],
    duration_delta[
      ,
      .(
        sensitivity_domain =
          "Pragmatic duration backbone",
        comparison =
          duration_label,
        metric =
          "Median delta MAE days",
        value =
          median_delta_MAE_days,
        secondary_metric =
          median_delta_pinball
      )
    ]
  ),
  fill = TRUE
)

fwrite(
  sensitivity_summary,
  file.path(
    out_dir,
    "12_KEY_SENSITIVITY_SUMMARY_DATA.csv"
  )
)

# -----------------------------------------------------------------------------
# Output inventory
# -----------------------------------------------------------------------------

inventory <- data.table(
  file = c(
    "01_CLASSIFICATION_YEAR_SPECIFIC_METRICS.csv",
    "02_CLASSIFICATION_POOLED_OOF_METRICS.csv",
    "03_2024_HEADLINE_CLASSIFICATION_BOOTSTRAP_CI.csv",
    "04_2024_FLEXIBLE_CALIBRATION_CURVES.csv",
    "05_2024_CALIBRATION_DECILE_POINTS.csv",
    "06_DURATION_YEAR_SPECIFIC_METRICS.csv",
    "07_2024_DURATION_BOOTSTRAP_CI.csv",
    "08_2024_DURATION_CALIBRATION_BINS.csv",
    "09_TEMPORAL_PERFORMANCE_FIGURE_DATA.csv",
    "10_2024_SUBGROUP_ROBUSTNESS_HEATMAP_DATA.csv",
    "11_2024_SOCIAL_AUGMENTATION_CALIBRATION_SHIFT_DATA.csv",
    "12_KEY_SENSITIVITY_SUMMARY_DATA.csv"
  ),
  intended_use = c(
    "Supplement performance table",
    "Main performance table candidate",
    "Main classification performance table confidence intervals",
    "Main calibration figure",
    "Calibration figure visual anchors",
    "Supplement duration temporal table",
    "Main duration table confidence intervals",
    "Main duration calibration figure",
    "Main temporal-stability figure",
    "Supplement subgroup heatmap",
    "Supplement or main fairness/context figure",
    "Supplement sensitivity summary"
  )
)

fwrite(
  inventory,
  file.path(
    out_dir,
    "13_OUTPUT_DATA_INVENTORY.csv"
  )
)

writeLines(
  c(
    "TBI-TRACT MANUSCRIPT OUTPUT DATA COMPLETE",
    "",
    "No models were fit or tuned in this script.",
    "All performance outputs derive from the locked rolling-origin prediction caches.",
    "",
    "Primary manuscript candidates:",
    "  02_CLASSIFICATION_POOLED_OOF_METRICS.csv",
    "  03_2024_HEADLINE_CLASSIFICATION_BOOTSTRAP_CI.csv",
    "  04_2024_FLEXIBLE_CALIBRATION_CURVES.csv",
    "  07_2024_DURATION_BOOTSTRAP_CI.csv",
    "  08_2024_DURATION_CALIBRATION_BINS.csv",
    "  09_TEMPORAL_PERFORMANCE_FIGURE_DATA.csv",
    "",
    "Calibration curves are flexible spline curves.",
    "Grouped calibration points are provided only as visual anchors, not as a substitute for the smooth curve.",
    "",
    "Q10-Q90 duration outputs should be described as estimated 10th-90th percentile ranges;",
    "empirical coverage is reported rather than assuming exact nominal 80% coverage."
  ),
  file.path(
    out_dir,
    "MANUSCRIPT_OUTPUT_DATA_SUMMARY.txt"
  )
)

cat("\nDONE: ", out_dir, "\n", sep = "")
