# ============================================================
# SPINE-TRACT: Spine Trauma Resource and Acute Care Trajectory Calculator
# Clinician-facing Shiny app template for shinyapps.io deployment
#
# Required files in data/:
#   - model_bundle.rds
#   - predictor_metadata.rds
#
# Optional files:
#   - manifest.json  # generated by rsconnect::writeManifest() or deployment tooling
#   - www/ohsu_logo.png
#
# This app is intentionally metadata-driven. It mirrors the TBI calculator
# deployment pattern while avoiding hard-coded dependence on a specific
# local analysis environment.
# ============================================================

suppressPackageStartupMessages({
  library(shiny)
  library(bslib)
  library(data.table)
  library(Matrix)
  library(xgboost)
  library(scales)
  library(stringr)
})

`%||%` <- function(x, y) if (is.null(x)) y else x

# ------------------------------------------------------------
# Load model bundle and predictor metadata
# ------------------------------------------------------------

bundle_path <- file.path("data", "model_bundle.rds")
metadata_path <- file.path("data", "predictor_metadata.rds")

if (!file.exists(bundle_path)) {
  stop(
    paste0(
      "Could not find data/model_bundle.rds.\n\n",
      "Place the locked SPINE-TRACT model bundle at: ",
      normalizePath(bundle_path, winslash = "/", mustWork = FALSE)
    ),
    call. = FALSE
  )
}

if (!file.exists(metadata_path)) {
  stop(
    paste0(
      "Could not find data/predictor_metadata.rds.\n\n",
      "Place the SPINE-TRACT predictor metadata at: ",
      normalizePath(metadata_path, winslash = "/", mustWork = FALSE)
    ),
    call. = FALSE
  )
}

bundle <- readRDS(bundle_path)
meta_obj <- readRDS(metadata_path)

metadata <- as.data.table(meta_obj$metadata %||% meta_obj)
required_metadata_cols <- c(
  "variable", "label", "group", "input_type", "model_type",
  "choices", "default", "min", "max", "app_order"
)
for (nm in required_metadata_cols) {
  if (!nm %in% names(metadata)) metadata[, (nm) := NA_character_]
}

metadata[, variable := as.character(variable)]
metadata <- metadata[!is.na(variable) & nzchar(variable)]
metadata[, label := fifelse(is.na(label) | !nzchar(label), variable, as.character(label))]
metadata[, group := fifelse(is.na(group) | !nzchar(group), "Other inputs", as.character(group))]
metadata[, input_type := fifelse(is.na(input_type) | !nzchar(input_type), "auto", as.character(input_type))]
metadata[, choices := as.character(choices)]
metadata[, default := as.character(default)]
metadata[, app_order_num := suppressWarnings(as.numeric(app_order))]
metadata[is.na(app_order_num), app_order_num := 9999]

# ------------------------------------------------------------
# Spine-specific label/group polish
# ------------------------------------------------------------

label_map <- c(
  age = "Age, years",
  sex_clean = "Sex",
  race_clean = "Race",
  ethnicity_clean = "Ethnicity",
  insurance_clean = "Insurance",
  transfer_clean = "Interfacility transfer",
  mechanism_clean = "Mechanism of injury",
  gcs_eye_clean = "GCS eye",
  gcs_motor_clean = "GCS motor",
  gcs_verbal_clean = "GCS verbal",
  gcs_total_aug = "Total GCS",
  pupil_clean = "Pupillary response",
  sbp_clean = "Systolic blood pressure, mmHg",
  pulse_clean = "Heart rate, beats/min",
  rr_clean = "Respiratory rate, breaths/min",
  spo2_clean = "Oxygen saturation, %",
  respiratoryassistance_clean = "Respiratory assistance on arrival",
  bleeding_disorder = "Bleeding disorder / coagulopathy",
  diabetes = "Diabetes",
  copd = "COPD",
  hypertension = "Hypertension",
  current_smoker = "Current smoker",
  dx_thoracic_vertebral_fracture = "Thoracic vertebral fracture",
  dx_lumbar_vertebral_fracture = "Lumbar vertebral fracture",
  dx_both_tl_fracture_levels = "Both thoracic and lumbar fracture levels",
  dx_tl_neural_injury = "Thoracolumbar neural injury",
  dx_tl_spinal_cord_injury = "Thoracolumbar spinal cord injury",
  dx_cauda_equina_or_nerve_root = "Cauda equina or nerve-root injury",
  dx_fracture_with_tl_neural_injury = "Fracture with thoracolumbar neural injury",
  dx_cervical_spine_injury = "Concomitant cervical spine injury",
  dx_tbi = "Concomitant TBI",
  dx_intracranial_hemorrhage_any = "Concomitant intracranial hemorrhage",
  dx_thoracic_injury = "Thoracic injury",
  dx_rib_fracture = "Rib fracture",
  dx_multiple_rib_fractures = "Multiple rib fractures",
  dx_flail_chest = "Flail chest",
  dx_pulmonary_contusion_laceration = "Pulmonary contusion/laceration",
  dx_pneumothorax_hemothorax = "Pneumothorax/hemothorax",
  dx_major_thoracic_organ_vascular = "Major thoracic organ/vascular injury",
  dx_abdominal_pelvic_injury = "Abdominal/pelvic injury",
  dx_upper_extremity_injury = "Upper-extremity injury",
  dx_lower_extremity_injury = "Lower-extremity injury"
)

ui_group_map <- c(
  age = "Demographics",
  sex_clean = "Demographics",
  race_clean = "Demographics",
  ethnicity_clean = "Demographics",
  insurance_clean = "Demographics",
  transfer_clean = "Transfer and mechanism",
  mechanism_clean = "Transfer and mechanism",
  gcs_eye_clean = "Neurologic status",
  gcs_motor_clean = "Neurologic status",
  gcs_verbal_clean = "Neurologic status",
  gcs_total_aug = "Neurologic status",
  pupil_clean = "Neurologic status",
  sbp_clean = "Vital signs and respiratory support",
  pulse_clean = "Vital signs and respiratory support",
  rr_clean = "Vital signs and respiratory support",
  spo2_clean = "Vital signs and respiratory support",
  respiratoryassistance_clean = "Vital signs and respiratory support",
  bleeding_disorder = "Comorbidities",
  diabetes = "Comorbidities",
  copd = "Comorbidities",
  hypertension = "Comorbidities",
  current_smoker = "Comorbidities"
)

metadata[variable %in% names(label_map), label := unname(label_map[variable])]
metadata[variable %in% names(ui_group_map), group := unname(ui_group_map[variable])]
metadata[grepl("thoracic|lumbar|spine|cauda|nerve_root", variable, ignore.case = TRUE), group := "Thoracolumbar spine phenotype"]
metadata[grepl("rib|flail|pulmonary|pneumo|hemo|thoracic", variable, ignore.case = TRUE) & !variable %in% names(ui_group_map), group := "Thoracic and pulmonary injuries"]
metadata[grepl("tbi|intracranial|abdomen|pelvic|extremity|polyregion|fracture_region", variable, ignore.case = TRUE) & !grepl("thoracic|lumbar|spine|cauda|nerve_root|rib|pulmonary|pneumo|hemo", variable, ignore.case = TRUE), group := "Concomitant injury profile"]
metadata[grepl("preexisting|comorbid|smoker|copd|diabetes|hypertension|bleeding", variable, ignore.case = TRUE), group := "Comorbidities"]

# ------------------------------------------------------------
# Endpoint/model helpers
# ------------------------------------------------------------

clip_prob <- function(p, eps = 1e-6) {
  pmin(pmax(as.numeric(p), eps), 1 - eps)
}

apply_binary_recalibration <- function(p, obj) {
  cal <- obj$calibration %||% obj$recalibration %||% NULL
  if (is.null(cal)) return(clip_prob(p))

  intercept <- suppressWarnings(as.numeric(cal$intercept %||% cal$alpha %||% NA_real_))
  slope <- suppressWarnings(as.numeric(cal$slope %||% cal$beta %||% NA_real_))
  eps <- suppressWarnings(as.numeric(cal$clip_eps %||% 1e-6))

  if (!is.finite(intercept) || !is.finite(slope)) return(clip_prob(p))
  if (!is.finite(eps) || eps <= 0 || eps >= 0.5) eps <- 1e-6

  as.numeric(plogis(intercept + slope * qlogis(clip_prob(p, eps))))
}

find_xgb <- function(obj, max_depth = 10) {
  if (max_depth < 0 || is.null(obj)) return(NULL)
  if (inherits(obj, "xgb.Booster")) return(obj)
  if (is.list(obj)) {
    for (nm in names(obj)) {
      hit <- find_xgb(obj[[nm]], max_depth - 1)
      if (!is.null(hit)) return(hit)
    }
  }
  NULL
}

get_model <- function(obj) {
  model <- find_xgb(obj)
  if (is.null(model)) stop("Could not find xgb.Booster in endpoint object.", call. = FALSE)
  model
}

pick_endpoint_obj <- function(candidates) {
  nms <- names(bundle)
  for (cand in candidates) {
    if (cand %in% nms) return(bundle[[cand]])
  }
  for (cand in candidates) {
    hit <- nms[tolower(nms) == tolower(cand)][1]
    if (!is.na(hit)) return(bundle[[hit]])
  }
  NULL
}

pick_endpoint_name <- function(candidates) {
  nms <- names(bundle)
  for (cand in candidates) {
    if (cand %in% nms) return(cand)
  }
  for (cand in candidates) {
    hit <- nms[tolower(nms) == tolower(cand)][1]
    if (!is.na(hit)) return(hit)
  }
  candidates[1]
}

endpoint_specs <- list(
  discharge = list(
    label = "Discharge disposition",
    type = "multiclass",
    candidates = c("discharge", "discharge_disposition", "discharge_model", "discharge_multiclass")
  ),
  icu_admission = list(
    label = "ICU admission",
    type = "binary",
    candidates = c("icu_admission", "icu", "icu_admit")
  ),
  mechanical_ventilation = list(
    label = "Mechanical ventilation",
    type = "binary",
    candidates = c("mechanical_ventilation", "mech_vent", "ventilation")
  ),
  hlos_ge20 = list(
    label = "Hospital LOS ≥20 days",
    type = "binary",
    candidates = c("hlos_ge20", "hospital_los_ge20", "hospital_los_20")
  ),
  icu_los_ge8 = list(
    label = "ICU LOS ≥8 days",
    type = "binary",
    candidates = c("icu_los_ge8", "icu_los_ge8_full", "icu_los_8")
  ),
  vent_days_ge8 = list(
    label = "Ventilator duration ≥8 days",
    type = "binary",
    candidates = c("vent_days_ge8", "vent_days_ge8_full", "ventilator_days_ge8", "ventilator_duration_ge8")
  ),
  operative_spine_intervention = list(
    label = "Operative spine intervention",
    type = "binary",
    candidates = c("operative_spine_intervention", "spine_operation", "operative_spine", "surgery")
  )
)

available_endpoints <- names(Filter(function(spec) !is.null(pick_endpoint_obj(spec$candidates)), endpoint_specs))
if (length(available_endpoints) == 0) {
  stop("No recognized SPINE-TRACT endpoint objects were found in model_bundle.rds.", call. = FALSE)
}

get_endpoint_obj <- function(endpoint) {
  spec <- endpoint_specs[[endpoint]]
  obj <- pick_endpoint_obj(spec$candidates)
  if (is.null(obj)) stop("Endpoint not found in model bundle: ", endpoint, call. = FALSE)
  obj
}

get_predictors <- function(endpoint, obj) {
  preds <- obj$predictors %||% obj$raw_predictors %||% NULL
  if (!is.null(preds) && length(preds) > 0) return(as.character(preds))

  if (endpoint == "mechanical_ventilation") {
    preds <- meta_obj$predictors_no_resp %||% meta_obj$predictors_full %||% NULL
  } else {
    preds <- meta_obj$predictors_full %||% NULL
  }
  if (!is.null(preds) && length(preds) > 0) return(as.character(preds))

  unique(metadata$variable)
}

get_feature_names <- function(obj, model) {
  fn <- obj$feature_names %||% model$feature_names %||% NULL
  if (!is.null(fn) && length(fn) > 0) return(as.character(fn))
  NULL
}

# ------------------------------------------------------------
# Input/default helpers
# ------------------------------------------------------------

split_choices <- function(x, fallback = character(0)) {
  if (is.null(x) || length(x) == 0 || is.na(x[1]) || !nzchar(as.character(x[1]))) return(fallback)
  out <- unlist(strsplit(as.character(x[1]), "\\|\\|"))
  out <- out[!is.na(out) & nzchar(out)]
  if (length(out) == 0) fallback else out
}

first_or <- function(x, fallback) {
  x <- x[!is.na(x) & nzchar(as.character(x))]
  if (length(x) == 0) fallback else as.character(x[1])
}

safe_numeric <- function(x, default = 0) {
  if (is.null(x) || length(x) == 0) return(default)
  y <- suppressWarnings(as.numeric(x[[1]]))
  if (!is.finite(y)) return(default)
  y
}

safe_int01 <- function(x) {
  if (is.null(x) || length(x) == 0) return(0L)
  as.integer(as.character(x[[1]]) %in% c("1", "Yes", "yes", "TRUE", "true", TRUE))
}

input_id <- function(v) paste0("var__", v)

is_yesno_var <- function(row) {
  choices <- split_choices(row$choices, character(0))
  identical(sort(choices), c("0", "1")) ||
    tolower(row$input_type) %in% c("yesno", "checkbox", "binary") ||
    grepl("^(dx_|ais_|has_|any_)", row$variable) ||
    row$variable %in% c("bleeding_disorder", "diabetes", "copd", "hypertension", "current_smoker")
}

is_numeric_var <- function(row) {
  tolower(row$input_type) %in% c("numeric", "integer", "continuous", "gcs_select", "ais_severity") ||
    grepl("age|gcs|sbp|pulse|rr|spo2|count|burden|score|number|n_", row$variable, ignore.case = TRUE)
}

default_for <- function(v) {
  row <- metadata[variable == v][1]
  if (nrow(row) == 0) return(0)

  choices <- split_choices(row$choices, character(0))
  def <- as.character(row$default)
  if (is.na(def) || !nzchar(def)) def <- NA_character_

  if (is_yesno_var(row)) return(first_or(def, "0"))
  if (length(choices) > 0) return(first_or(def[def %in% choices], choices[1]))
  if (is_numeric_var(row)) return(safe_numeric(def, 0))
  first_or(def, "0")
}

visible_vars <- metadata[
  !tolower(input_type) %in% c("derived", "hidden", "none") &
    !grepl("_aug$|^n_|count|burden", variable, ignore.case = TRUE),
  variable
]

# Ensure likely clinically important variables are shown even if metadata is sparse.
visible_vars <- unique(c(
  intersect(c(
    "age", "sex_clean", "race_clean", "ethnicity_clean", "insurance_clean",
    "transfer_clean", "mechanism_clean",
    "gcs_eye_clean", "gcs_motor_clean", "gcs_verbal_clean", "gcs_total_aug", "pupil_clean",
    "sbp_clean", "pulse_clean", "rr_clean", "spo2_clean", "respiratoryassistance_clean",
    "bleeding_disorder", "diabetes", "copd", "hypertension", "current_smoker"
  ), metadata$variable),
  visible_vars
))

metadata[, is_visible_app := variable %in% visible_vars]

make_input <- function(row) {
  v <- row$variable
  label <- row$label
  id <- input_id(v)
  choices <- split_choices(row$choices, character(0))
  def <- default_for(v)

  if (is_yesno_var(row)) {
    return(selectInput(id, label, choices = c("No" = "0", "Yes" = "1"), selected = as.character(def)))
  }

  if (length(choices) > 0 && !is_numeric_var(row)) {
    return(selectInput(id, label, choices = stats::setNames(choices, choices), selected = as.character(def)))
  }

  min_val <- suppressWarnings(as.numeric(row$min))
  max_val <- suppressWarnings(as.numeric(row$max))
  if (!is.finite(min_val)) min_val <- NA_real_
  if (!is.finite(max_val)) max_val <- NA_real_

  numericInput(
    id,
    label,
    value = safe_numeric(def, 0),
    min = min_val,
    max = max_val,
    step = if (grepl("age|gcs|count|score|burden", v, ignore.case = TRUE)) 1 else NA
  )
}

# ------------------------------------------------------------
# Derived values
# ------------------------------------------------------------

get_val <- function(row, v) row[[v]] %||% default_for(v)
get_yesno <- function(row, v) safe_int01(row[[v]] %||% default_for(v))

pick_choice <- function(v, pattern, fallback = NULL) {
  row <- metadata[variable == v][1]
  choices <- split_choices(row$choices, character(0))
  if (length(choices) == 0) return(fallback %||% 0)
  hit <- choices[grepl(pattern, choices, ignore.case = TRUE)][1]
  if (is.na(hit)) choices[1] else hit
}

derive_age_group <- function(age, v) {
  choices <- split_choices(metadata[variable == v][1]$choices, character(0))
  if (length(choices) == 0) return(default_for(v))
  age <- safe_numeric(age, NA_real_)
  if (!is.finite(age)) return(default_for(v))
  if (age < 40) return(first_or(choices[grepl("18|39|young", choices, ignore.case = TRUE)], choices[1]))
  if (age < 65) return(first_or(choices[grepl("40|64|adult", choices, ignore.case = TRUE)], choices[1]))
  if (age < 75) return(first_or(choices[grepl("65|74", choices, ignore.case = TRUE)], choices[1]))
  first_or(choices[grepl("75|80|older|elder", choices, ignore.case = TRUE)], choices[length(choices)])
}

derive_gcs_severity <- function(gcs, v) {
  choices <- split_choices(metadata[variable == v][1]$choices, character(0))
  if (length(choices) == 0) return(default_for(v))
  gcs <- safe_numeric(gcs, NA_real_)
  if (!is.finite(gcs)) return(default_for(v))
  if (gcs >= 13) return(first_or(choices[grepl("mild|13", choices, ignore.case = TRUE)], choices[1]))
  if (gcs >= 9) return(first_or(choices[grepl("moderate|9", choices, ignore.case = TRUE)], choices[1]))
  first_or(choices[grepl("severe|3", choices, ignore.case = TRUE)], choices[1])
}

build_patient_row <- function(input) {
  vars <- unique(metadata$variable)
  row <- as.list(stats::setNames(lapply(vars, default_for), vars))

  for (v in visible_vars) {
    id <- input_id(v)
    if (!is.null(input[[id]])) row[[v]] <- input[[id]]
  }

  # Standard derived variables used in the modeling pipeline.
  if ("age_group_aug" %in% vars) row$age_group_aug <- derive_age_group(row$age, "age_group_aug")
  if ("gcs_severity_aug" %in% vars) row$gcs_severity_aug <- derive_gcs_severity(row$gcs_total_aug, "gcs_severity_aug")
  if ("hypotension_sbp90_aug" %in% vars) row$hypotension_sbp90_aug <- as.integer(safe_numeric(row$sbp_clean, 999) < 90)
  if ("hypoxia_spo2_90_aug" %in% vars) row$hypoxia_spo2_90_aug <- as.integer(safe_numeric(row$spo2_clean, 999) <= 90)
  if ("tachycardia_120_aug" %in% vars) row$tachycardia_120_aug <- as.integer(safe_numeric(row$pulse_clean, 0) >= 120)
  if ("abnormal_rr_aug" %in% vars) {
    rr <- safe_numeric(row$rr_clean, 16)
    row$abnormal_rr_aug <- as.integer(rr < 10 | rr > 29)
  }

  if ("n_preexisting_conditions" %in% vars) {
    comorb <- c("bleeding_disorder", "diabetes", "copd", "hypertension", "current_smoker")
    row$n_preexisting_conditions <- sum(vapply(comorb[comorb %in% vars], function(v) get_yesno(row, v), numeric(1)), na.rm = TRUE)
  }

  # Common thoracolumbar phenotype aggregations. If names differ, the metadata default is retained.
  thoracic_fx <- get_yesno(row, "dx_thoracic_vertebral_fracture")
  lumbar_fx <- get_yesno(row, "dx_lumbar_vertebral_fracture")
  sci <- max(get_yesno(row, "dx_tl_spinal_cord_injury"), get_yesno(row, "dx_thoracolumbar_spinal_cord_injury"), na.rm = TRUE)
  cauda <- max(get_yesno(row, "dx_cauda_equina_or_nerve_root"), get_yesno(row, "dx_cauda_equina_injury"), get_yesno(row, "dx_nerve_root_injury"), na.rm = TRUE)
  neural_any <- as.integer(sci == 1L || cauda == 1L)

  if ("dx_both_tl_fracture_levels" %in% vars) row$dx_both_tl_fracture_levels <- as.integer(thoracic_fx == 1L && lumbar_fx == 1L)
  if ("dx_tl_neural_injury" %in% vars) row$dx_tl_neural_injury <- neural_any
  if ("dx_fracture_with_tl_neural_injury" %in% vars) row$dx_fracture_with_tl_neural_injury <- as.integer((thoracic_fx == 1L || lumbar_fx == 1L) && neural_any == 1L)

  # Generic count/polyregion helpers for models that use ICD-derived burden variables.
  dx_vars <- vars[grepl("^dx_", vars)]
  visible_dx <- dx_vars[dx_vars %in% visible_vars]
  if ("n_unique_icd_dx_codes" %in% vars) row$n_unique_icd_dx_codes <- sum(vapply(visible_dx, function(v) get_yesno(row, v), numeric(1)), na.rm = TRUE)
  if ("n_traumatic_icd_dx_codes" %in% vars) row$n_traumatic_icd_dx_codes <- sum(vapply(visible_dx, function(v) get_yesno(row, v), numeric(1)), na.rm = TRUE)

  injury_regions <- c(
    spine = as.integer(thoracic_fx == 1L || lumbar_fx == 1L || neural_any == 1L),
    head = max(get_yesno(row, "dx_tbi"), get_yesno(row, "dx_intracranial_hemorrhage_any"), na.rm = TRUE),
    thorax = max(get_yesno(row, "dx_thoracic_injury"), get_yesno(row, "dx_rib_fracture"), get_yesno(row, "dx_pneumothorax_hemothorax"), na.rm = TRUE),
    abdomen = get_yesno(row, "dx_abdominal_pelvic_injury"),
    upper = get_yesno(row, "dx_upper_extremity_injury"),
    lower = get_yesno(row, "dx_lower_extremity_injury")
  )
  region_count <- sum(injury_regions > 0, na.rm = TRUE)
  if ("dx_polyregion_injury_count" %in% vars) row$dx_polyregion_injury_count <- region_count
  if ("dx_polyregion_2plus" %in% vars) row$dx_polyregion_2plus <- as.integer(region_count >= 2)
  if ("dx_polyregion_3plus" %in% vars) row$dx_polyregion_3plus <- as.integer(region_count >= 3)
  if ("fracture_region_count" %in% vars) row$fracture_region_count <- sum(c(thoracic_fx, lumbar_fx, get_yesno(row, "dx_rib_fracture"), get_yesno(row, "dx_upper_extremity_injury"), get_yesno(row, "dx_lower_extremity_injury")) > 0, na.rm = TRUE)

  as.data.table(row)
}

prepare_model_data <- function(row, predictors) {
  predictors <- unique(as.character(predictors))
  for (v in setdiff(predictors, names(row))) row[, (v) := default_for(v)]
  x <- copy(row[, ..predictors])

  for (v in names(x)) {
    meta_row <- metadata[variable == v][1]
    choices <- if (nrow(meta_row) > 0) split_choices(meta_row$choices, character(0)) else character(0)
    if (length(choices) > 0 && !is_numeric_var(meta_row)) {
      x[[v]] <- factor(as.character(x[[v]]), levels = choices)
    } else if (is_yesno_var(meta_row) || is_numeric_var(meta_row)) {
      x[[v]] <- suppressWarnings(as.numeric(x[[v]]))
      x[[v]][!is.finite(x[[v]])] <- safe_numeric(default_for(v), 0)
    } else {
      x[[v]] <- as.character(x[[v]])
    }
  }

  x
}

make_sparse_matrix <- function(x, feature_names = NULL) {
  mm <- sparse.model.matrix(~ . - 1, data = as.data.frame(x))
  if (!is.null(feature_names)) {
    missing <- setdiff(feature_names, colnames(mm))
    if (length(missing) > 0) {
      zero <- Matrix(0, nrow = nrow(mm), ncol = length(missing), sparse = TRUE)
      colnames(zero) <- missing
      mm <- cbind(mm, zero)
    }
    extra <- setdiff(colnames(mm), feature_names)
    if (length(extra) > 0) mm <- mm[, setdiff(colnames(mm), extra), drop = FALSE]
    mm <- mm[, feature_names, drop = FALSE]
  }
  mm
}

predict_endpoint <- function(endpoint, row) {
  spec <- endpoint_specs[[endpoint]]
  obj <- get_endpoint_obj(endpoint)
  model <- get_model(obj)
  predictors <- get_predictors(endpoint, obj)
  feature_names <- get_feature_names(obj, model)
  x <- prepare_model_data(row, predictors)
  mm <- make_sparse_matrix(x, feature_names)
  pred <- predict(model, xgb.DMatrix(mm))

  if (spec$type == "multiclass") {
    levels <- obj$class_levels %||% obj$levels %||% meta_obj$discharge_levels %||% c("Home/home health", "Post-acute facility", "Death/hospice")
    pred <- as.numeric(pred)
    if (length(pred) != length(levels)) {
      pred <- pred[seq_len(min(length(pred), length(levels)))]
      levels <- levels[seq_along(pred)]
    }
    pred <- pred / sum(pred)
    return(data.table(endpoint = spec$label, outcome = levels, probability = pred))
  }

  p <- apply_binary_recalibration(as.numeric(pred[1]), obj)
  data.table(endpoint = spec$label, outcome = "Yes", probability = p)
}

fmt_prob <- function(p) percent(p, accuracy = 0.1)

risk_band <- function(p) {
  if (is.na(p)) return("Unavailable")
  if (p < 0.05) "Low"
  else if (p < 0.15) "Moderate"
  else if (p < 0.30) "Elevated"
  else "High"
}

# ------------------------------------------------------------
# UI
# ------------------------------------------------------------

logo_ui <- if (file.exists(file.path("www", "ohsu_logo.png"))) {
  img(src = "ohsu_logo.png", class = "ohsu-logo")
} else {
  div("OHSU", class = "ohsu-logo-fallback")
}

endpoint_choices <- stats::setNames(
  available_endpoints,
  vapply(available_endpoints, function(x) endpoint_specs[[x]]$label, character(1))
)

grouped_inputs <- function() {
  md <- metadata[is_visible_app == TRUE][order(group, app_order_num, label)]
  groups <- split(md, md$group)
  lapply(names(groups), function(g) {
    card(
      class = "input-card",
      card_header(g),
      card_body(lapply(seq_len(nrow(groups[[g]])), function(i) make_input(groups[[g]][i])))
    )
  })
}

ui <- page_fluid(
  theme = bs_theme(
    version = 5,
    bootswatch = "flatly",
    base_font = font_google("Inter"),
    heading_font = font_google("Inter"),
    primary = "#1f4e79",
    bg = "#f4f7fb",
    fg = "#243447"
  ),
  tags$head(
    tags$meta(name = "viewport", content = "width=device-width, initial-scale=1"),
    tags$style(HTML("\n      :root {\n        --page-max: 1360px;\n        --card-radius: 24px;\n        --shadow-soft: 0 8px 28px rgba(31, 52, 73, 0.07);\n        --border-soft: #e7edf5;\n        --text-main: #243447;\n        --text-muted: #5b6b7f;\n        --accent: #1f4e79;\n      }\n      body { background: #f4f7fb; }\n      .app-container { max-width: var(--page-max); margin: 0 auto; padding: 24px 22px 36px 22px; }\n      .app-header { background: #ffffff; border-radius: 28px; padding: clamp(18px, 2.2vw, 30px); margin-bottom: 24px; box-shadow: var(--shadow-soft); border: 1px solid var(--border-soft); }\n      .header-grid { display: grid; grid-template-columns: minmax(70px, 96px) 1fr; gap: 20px; align-items: center; }\n      .logo-wrap { display: flex; align-items: center; justify-content: center; }\n      .ohsu-logo { width: clamp(58px, 6vw, 92px); height: auto; display: block; }\n      .ohsu-logo-fallback { width: 88px; height: 88px; border-radius: 22px; display: flex; align-items: center; justify-content: center; background: #1f4e79; color: white; font-weight: 900; letter-spacing: 0.06em; }\n      .header-title { margin: 0 0 8px 0; font-weight: 800; line-height: 1.04; font-size: clamp(1.9rem, 3.4vw, 3.2rem); color: var(--text-main); max-width: 1000px; }\n      .ohsu-subtitle { color: var(--text-muted); margin: 0 0 3px 0; font-size: 1.05rem; }\n      .input-card, .metric-card, .plot-card, .detail-card { background: #ffffff; border: 1px solid var(--border-soft) !important; border-radius: var(--card-radius) !important; box-shadow: var(--shadow-soft); margin-bottom: 18px; }\n      .sticky-panel { position: sticky; top: 24px; max-height: calc(100vh - 48px); overflow-y: auto; padding-right: 4px; scrollbar-width: thin; }\n      .form-label { font-weight: 650; color: #2f4257; margin-bottom: 5px; font-size: 0.97rem; }\n      .form-control, .form-select { border-radius: 14px !important; border: 1px solid #d4dde8 !important; min-height: 44px; box-shadow: none !important; }\n      .btn-primary { background-color: #245789 !important; border-color: #245789 !important; border-radius: 14px !important; font-weight: 750; min-height: 46px; margin-top: 6px; }\n      .metric-grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 14px; margin-bottom: 18px; }\n      .metric-card { padding: 20px; min-height: 120px; }\n      .metric-value { font-size: clamp(1.45rem, 2vw, 2.05rem); line-height: 1; font-weight: 800; color: var(--accent); margin-bottom: 10px; }\n      .metric-label { font-size: 0.92rem; color: var(--text-muted); line-height: 1.35; }\n      .small-muted { color: var(--text-muted); font-size: 0.92rem; line-height: 1.45; }\n      .table td, .table th { vertical-align: middle; }\n      @media (max-width: 1199px) { .sticky-panel { position: static; max-height: none; overflow-y: visible; padding-right: 0; } .metric-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); } }\n      @media (max-width: 767px) { .app-container { padding: 18px 14px 28px 14px; } .header-grid, .metric-grid { grid-template-columns: 1fr; } .header-grid { text-align: center; } }\n    "))
  ),
  div(
    class = "app-container",
    div(
      class = "app-header",
      div(
        class = "header-grid",
        div(class = "logo-wrap", logo_ui),
        div(
          h1("SPINE-TRACT", class = "header-title"),
          p("Spine Trauma Resource and Acute Care Trajectory Calculator", class = "ohsu-subtitle"),
          p("Admission-era estimates for adults with acute thoracolumbar spine trauma", class = "ohsu-subtitle")
        )
      )
    ),
    layout_columns(
      col_widths = c(4, 8),
      div(
        class = "sticky-panel",
        card(
          class = "input-card",
          card_header("Prediction target"),
          card_body(
            selectInput("endpoint", "Endpoint", choices = c("All endpoints" = "all", endpoint_choices), selected = "all"),
            actionButton("predict", "Update predictions", class = "btn-primary", width = "100%")
          )
        ),
        grouped_inputs()
      ),
      div(
        card(
          class = "plot-card",
          card_body(
            h2("Estimated resource-utilization trajectory", style = "font-weight:800;"),
            p("Outputs estimate observed resource use during hospitalization. They are not treatment recommendations.", class = "small-muted"),
            uiOutput("metric_cards"),
            tableOutput("prediction_table")
          )
        ),
        card(
          class = "detail-card",
          card_body(
            h3("Important interpretation"),
            tags$ul(
              tags$li("SPINE-TRACT estimates probabilities from the locked model bundle and aligned predictor metadata."),
              tags$li("ICU admission, ventilation, prolonged resource use, and operative intervention reflect observed resource trajectories, not clinical indication or appropriateness."),
              tags$li("The model was developed for adults with acute thoracolumbar spine trauma and should not be applied outside that population without validation.")
            )
          )
        )
      )
    )
  )
)

# ------------------------------------------------------------
# Server
# ------------------------------------------------------------

server <- function(input, output, session) {
  predictions <- eventReactive(input$predict, {
    row <- build_patient_row(input)
    endpoints <- if (identical(input$endpoint, "all")) available_endpoints else input$endpoint
    rbindlist(lapply(endpoints, function(ep) predict_endpoint(ep, row)), fill = TRUE)
  }, ignoreInit = FALSE)

  output$metric_cards <- renderUI({
    pred <- predictions()
    req(nrow(pred) > 0)

    if (input$endpoint == "discharge" || (input$endpoint == "all" && "discharge" %in% available_endpoints)) {
      discharge_rows <- pred[endpoint == endpoint_specs$discharge$label]
      if (nrow(discharge_rows) > 0) {
        top <- discharge_rows[which.max(probability)]
        main_cards <- list(
          div(class = "metric-card", div(class = "metric-value", fmt_prob(top$probability)), div(class = "metric-label", paste("Most likely disposition:", top$outcome)))
        )
      } else {
        main_cards <- list()
      }
    } else {
      main_cards <- list()
    }

    binary_rows <- pred[outcome == "Yes"]
    binary_cards <- lapply(seq_len(nrow(binary_rows)), function(i) {
      div(
        class = "metric-card",
        div(class = "metric-value", fmt_prob(binary_rows$probability[i])),
        div(class = "metric-label", binary_rows$endpoint[i]),
        div(class = "small-muted", paste("Risk band:", risk_band(binary_rows$probability[i])))
      )
    })

    div(class = "metric-grid", c(main_cards, binary_cards))
  })

  output$prediction_table <- renderTable({
    pred <- predictions()
    req(nrow(pred) > 0)
    out <- copy(pred)
    out[, Probability := fmt_prob(probability)]
    out[, `Risk band` := ifelse(outcome == "Yes", vapply(probability, risk_band, character(1)), "—")]
    setnames(out, c("endpoint", "outcome"), c("Endpoint", "Outcome"))
    out[, .(Endpoint, Outcome, Probability, `Risk band`)]
  }, striped = TRUE, bordered = FALSE, spacing = "m")
}

shinyApp(ui, server)
